### PR TITLE
Customizer-controlled homepage

### PR DESCRIPTION
**Pull request by benlk**
## Changes

- Removes all the old images from the theme's homepage directory
- Cachebusts the homepage CSS
- Adds Customizer controls for the homepage featured image and related text, drawing the image credit from the metadata fields in Largo's Navis Media Credit plugin that can be set upon image upload.

Screen Shot 2020-04-17 at 20 05 11
Screen Shot 2020-04-17 at 20 13 34

## Why

for #125 

## Questions

See questions in #125. Also:

- [ ] How should these fields be labeled? Right now they're kinda temporary labels and descriptions.

Note that, post-deploy, there will be no configured homepage.

## Testing

After checking out this branch, check the homepage with:

Image:
- [x] no image
- [x] image but no media credit
- [ ] image with:
    - [ ] media credit name only, not org or URL
    - [ ] media credit name and URL, not org
    - [ ] media credit name and org, but not URL
    - [ ] media credit name and org and URL
    - [ ] media credit org only, not name or URL
    - [ ] media credit URL only, not credit or org

Headline:
- [x] no headline
- [x] headline

Blurb:
- [x] no blurb
- [x] single-line blurb
- [x] blurb with double linebreaks in the textarea

Button:
- [x] no button text
- [x] button text

Link:
- [x] is there a way to require this?

### CODE REVIEW

**Comment by joshdarby** [comment]
A couple of questions:

- [ ] If the button text + link are both empty, should we hide the button?
Screen Shot 2020-04-20 at 12 22 40 PM
- [ ] If the button text is empty but the link field is filled, should the link url be used as the button text?
- [ ] Are media credit attributes supposed to show? I can't get any to appear.

**Comment by benlk** [comment]
Updated the code to cover the cases where:
- there is no headline: no h2 element
- there is no blurb: no blurb
- there is no button text: no button
- there is no link: error message

No-image still looks like a big white empty spot:

Screen Shot 2020-04-20 at 16 03 39

This screenshot shows off the error message text, as well as the improved descriptions for the various inputs.

**Comment by benlk** [comment]
> Are media credit attributes supposed to show? I can't get any to appear.

@joshdarby Are you setting them when uploading the image?

Screen Shot 2020-04-20 at 15 26 32

**Comment by joshdarby** [comment]
> Are you setting them when uploading the image?

@benlk No, I was setting them while choosing an image to use. I'll try uploading a new image and setting them there.

**Comment by benlk** [comment]
> No, I was setting them while choosing an image to use. 

That's bothersome; I wonder if it's a bug in Largo?

**Comment by benlk** [comment]
Now includes a fix for https://github.com/INN/inn/blob/92015727927463627355e88e88774a44e7ac76b9/functions.php#L268-L284:

> <b>Warning</b>:  array_key_exists(): The first argument should be either a string or an integer in <b>/umbrella-inndev/wp-content/themes/inn/functions.php</b> on line <b>279</b><br />

**Comment by benlk** [comment]
Upon deploy, set this up with the settings from https://github.com/INN/inn/issues/124

**Pull request merged**
