### PR TITLE
Switching filter to jquery

### PR DESCRIPTION
**Pull request by rclations**
Available for review on staging

### CODE REVIEW

**Comment by julia67** [comment]
Noticed a couple issues, mostly related to filter state.

**Observed:** If, after you've filtered the list, you click into a member and then return to /members, the dropdowns show the previous selections, but the page displays the unfiltered list of all members.
**Expected:** The page should display the filtered list. Probably want to fire the "change" event for the select box on $(document).ready()
screen shot 2017-06-15 at 10 42 27 am

**Observed:** When there are no results, the user feedback is displayed in a popup alert.
**Expected:** Display the feedback in the page content instead of a popup.

**Observed:**  Are the members tagged appropriately by category? "Crime" returns 120 results, and if, for example, I click into Honolulu Civil Beat, "crime" isn't listed as a focus area. Or: "Signcasts" shows up under the "Technology" filter, but "technology" isn't listed as a focus area on the Signcasts page.
**Expected:** The focus area should only show results that list said focus area.

_I expect this is the same tagging problem:_
**Observed:** Crime + Kansas returns a health org
**Expected:** Crime + Kansas should return an empty result / "no members matched" message
screen shot 2017-06-15 at 11 03 17 am

**Observed:** Nebraska is listed in the state dropdown even though there are no members in Nebraska.
**Expected:** Disable select options for irrelevant choices.

**Comment by rclations** [comment]
added section headings for the issues above to make it easier to follow subsequent replies

**Comment by kaylima** [comment]
Please note that we'll be updating the member directory per Sue's request as part of the current redesign project for inn.org. Not sure if you want to wait on this until that's finalized...

**Comment by rclations** [comment]
any details about how we'll be updating it?

**Comment by rclations** [comment]
[X] ~~Filtering on page reload~~ (fixed with 2cac52f)
[ ] No results behavior
[ ] Category Tagging
[ ] Available Filter Options

**Comment by rclations** [comment]
I think these should all be fixed - ready for another review

**Pull request merged**
